spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/gdkm_linux?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#  url: jdbc:mysql://47.96.173.127/gdkm_linux?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 6379
    host: 127.0.0.1
#    host: 117.50.11.169
  mail:
    host: smtp.qq.com
    username: lzh421@qq.com
    password: kstfnozqjpxocajd
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gdkm.model
  configuration:
    map-underscore-to-camel-case: true
111
server:
  context-path: /linux
  port: 8888
thymeleaf:
  prefix: classpath:/templates/    #指定资源位置
  mode: LEGACYHTML5
projectUrl:
  linux: http://localhost:8888/linux

  imgUcloud: img
  shipinUcloud: shipin
  kejianUcloud: kejian
